### ISSUE TITLE
Setting default StatusBar color

### ISSUE THREAD

**Issue by sbaildon** [Rainrider/oUF_ArtifactPower#2]
I gave https://github.com/Rainrider/oUF_ArtifactPower/commit/7c6b964bfaba90523f6db960b0e15d4148770f32 a spin but I'm not sure it's working as intended. I created a new `StatusBar`, avoided calling `SetStatusBarColor`, but the bar always comes out as white.

Calling `GetStatusBarColor()` returns `0.999..., 0.999..., 0.999..., 0.999...` - it looks like you'll never get in to call `SetStatusBarColor()`

Also, how come you decided to go with hard coding the colour values over using `GetItemQualityColor(6)`?

**Comment by Rainrider** [comment]
The hard coded value is what [Blizzard uses](https://github.com/tomrus88/BlizzardInterfaceCode/blob/c9d5cf53f3165beb2850dfde793d531e4b9dbaec/Interface/FrameXML/MainMenuBar.xml#L487)
